default: &default
  adapter: postgresql
  encoding: unicode
  username: derek
  password: fakePasswordToAllowRakeAssetsPrecompile
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: good_carma_development

test:
  <<: *default
  database: good_carma_test

production:
  <<: *default
  database: good_carma_production

