default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.development[:database_username] %>
  password: <%= Rails.application.credentials.development[:database_password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: good_carma_development

test:
  <<: *default
  database: good_carma_test

production:
  <<: *default
  database: good_carma_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
